# Generated by Django 4.1 on 2022-12-03 06:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVSSRatings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=10)),
                ('base_score_min', models.FloatField()),
                ('base_score_max', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_hostname', models.CharField(max_length=20)),
                ('asset_ip_address', models.GenericIPAddressField()),
                ('title', models.CharField(max_length=300)),
                ('severity', models.CharField(max_length=10)),
                ('cvss', models.FloatField()),
                ('publication_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
